name: Test and Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    name: Jest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Using node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test:coverage
      - run: npm run lint:coverage
      - name: Run SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  # sonarcloud:
  #   name: Scan PR
  #   runs-on: ubuntu-latest
  #   needs: test-and-lint
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0 
  #     - name: Download coverage artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: coverage
  #         path: coverage/
  #     - name: Move coverage files
  #       shell: bash
  #       run: |
  #         mv coverage/* ./
  #     - name: Run SonarCloud
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}